version: '3'

services:
  backend:
    build: ./recedo-backend
    restart: unless-stopped
    mem_limit: '64M'
    cpus: 0.25
    volumes:
      - ./recedo-backend:/app
    ports:
      - 10000:10000
    command: npm start
  frontend:
    build: ./recedo-frontend
    restart: unless-stopped
    mem_limit: '64M'
    cpus: 0.25
    volumes:
      - ./recedo-frontend:/app
    ports:
      - 10010:80
    env_file:
      - recedo-frontend/.env
    environment:
      PORT: 10010
  # db:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #     MONGO_INITDB_DATABASE: recedo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodb:/data/db
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      