version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - 5010:5010
  db:
    image: mongo:latest
    environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
    - 27017:27017
    volumes:
    - mongodb_data_container:/data/db
      